eureka: 
  client: 
    serviceUrl: 
      #defaultZone: http://serviceregistry:8761/eureka
      defaultZone: http://localhost:8761/eureka
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 60000
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"
  security: 
    enabled: false
spring: 
  cloud: 
    config: 
      allowOverride: true
      overrideSystemProperties: false
