# Discovery client Properties
eureka:
   instance:
      prefer-ip-address: true
      # instance-id: ${spring.application.name}:${server.port}
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
           #defaultZone: http://serviceregistry:8761/eureka
           defaultZone: http://localhost:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 90000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 3000
  eureka:
      enabled: true

# Expose Endpoints for Actuator
management:
    endpoint:
        chaosmonkey:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
