# Discovery client Properties
#indicates the duration the server waits since it received the last heartbeat before it can evict an instance from its registry
#indicates the frequency the client sends heartbeats to indicate that it is still alive.
eureka:
   instance:
      prefer-ip-address: true
      # instance-id: ${spring.application.name}:${server.port}
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
           #defaultZone: http://serviceregistry:8761/eureka
           defaultZone: http://localhost:8761/eureka 

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 90000

#The read timeout in milliseconds. Default is 1000ms
#The Connection timeout in milliseconds. Default is 1000ms.
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 6000
  eureka:
      enabled: true
        
# Actuator End Points
management:
    endpoints:
        web:
            exposure:
                include: '*'

#this will help you load services eagerly. Otherwise for first time, we will get timeout exception.
#When path starts with /nsure/thirdpartyservice/**, redirect it to thirdpartyservice
#When path starts with /nsure/authenticationservice/**, redirect it to authenticationservice
zuul:
    routes:
      personservice: 
         service-id: personservice
         path: /personservice/**
